insert into users (id, name, description, creator_id) values (1, 'Piper''s Fleabane', 'Asteraceae', '5');
insert into users (id, name, description, creator_id) values (2, 'Pituri', 'Solanaceae', '8');
insert into users (id, name, description, creator_id) values (3, 'Closed Bottle Gentian', 'Gentianaceae', '8');
insert into users (id, name, description, creator_id) values (4, 'Common Hawkweed', 'Asteraceae', '7');
insert into users (id, name, description, creator_id) values (5, 'Rim Lichen', 'Lecanoraceae', '10');
insert into users (id, name, description, creator_id) values (6, 'Largeflower Goldenweed', 'Asteraceae', '2');
insert into users (id, name, description, creator_id) values (7, 'Sarmenthypnum Moss', 'Amblystegiaceae', '6');
insert into users (id, name, description, creator_id) values (8, 'Heath Wrightwort', 'Acanthaceae', '7');
insert into users (id, name, description, creator_id) values (9, 'Graylocks Four-nerve Daisy', 'Asteraceae', '3');
insert into users (id, name, description, creator_id) values (10, 'Chaparral False Bindweed', 'Convolvulaceae', '1');
insert into users (id, name, description, creator_id) values (11, 'Bulrush', 'Cyperaceae', '8');
insert into users (id, name, description, creator_id) values (12, 'Intermountain Rubberweed', 'Asteraceae', '5');
insert into users (id, name, description, creator_id) values (13, 'Silverhair Pineapplegrass', 'Liliaceae', '7');
insert into users (id, name, description, creator_id) values (14, 'Lecidea Lichen', 'Lecideaceae', '4');
insert into users (id, name, description, creator_id) values (15, 'Cascade Onion', 'Liliaceae', '2');
insert into users (id, name, description, creator_id) values (16, 'Thicket Bean', 'Fabaceae', '3');
insert into users (id, name, description, creator_id) values (17, 'Alkali Milkvetch', 'Fabaceae', '4');
insert into users (id, name, description, creator_id) values (18, 'Gray''s Biscuitroot', 'Apiaceae', '6');
insert into users (id, name, description, creator_id) values (19, 'Silverback Fern', 'Pteridaceae', '3');
insert into users (id, name, description, creator_id) values (20, 'Twoleaf Watermilfoil', 'Haloragaceae', '1');
