insert into maps (name, description, creator_id) values ( 'Piper''s Fleabane', 'Asteraceae', 5);
insert into maps (name, description, creator_id) values ( 'Pituri', 'Solanaceae', 8);
insert into maps (name, description, creator_id) values ( 'Closed Bottle Gentian', 'Gentianaceae', 8);
insert into maps (name, description, creator_id) values ( 'Common Hawkweed', 'Asteraceae', 7);
insert into maps (name, description, creator_id) values ( 'Rim Lichen', 'Lecanoraceae', 10);
insert into maps (name, description, creator_id) values ( 'Largeflower Goldenweed', 'Asteraceae', 2);
insert into maps (name, description, creator_id) values ( 'Sarmenthypnum Moss', 'Amblystegiaceae', 6);
insert into maps (name, description, creator_id) values ( 'Heath Wrightwort', 'Acanthaceae', 7);
insert into maps (name, description, creator_id) values ( 'Graylocks Four-nerve Daisy', 'Asteraceae', 3);
insert into maps (name, description, creator_id) values ( 'Chaparral False Bindweed', 'Convolvulaceae', 1);
insert into maps (name, description, creator_id) values ( 'Bulrush', 'Cyperaceae', 8);
insert into maps (name, description, creator_id) values ( 'Intermountain Rubberweed', 'Asteraceae', 5);
insert into maps (name, description, creator_id) values ( 'Silverhair Pineapplegrass', 'Liliaceae', 7);
insert into maps (name, description, creator_id) values ( 'Lecidea Lichen', 'Lecideaceae', 4);
insert into maps (name, description, creator_id) values ( 'Cascade Onion', 'Liliaceae', 2);
insert into maps (name, description, creator_id) values ( 'Thicket Bean', 'Fabaceae', 3);
insert into maps (name, description, creator_id) values ( 'Alkali Milkvetch', 'Fabaceae', 4);
insert into maps (name, description, creator_id) values ( 'Gray''s Biscuitroot', 'Apiaceae', 6);
insert into maps (name, description, creator_id) values ( 'Silverback Fern', 'Pteridaceae', 3);
insert into maps (name, description, creator_id) values ( 'Twoleaf Watermilfoil', 'Haloragaceae', 1);
